//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alertmeeting
    {
        public int alertID { get; set; }
        public System.DateTime meetingDate { get; set; }
        public string meetingTitle { get; set; }
        public string meetingDetail { get; set; }
        public string meetingSummary { get; set; }
        public int meetingByStaffID { get; set; }
    }
}
