//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class antidrugdbEntities : DbContext
    {
        public antidrugdbEntities()
            : base("name=antidrugdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alertmeeting> alertmeeting { get; set; }
        public virtual DbSet<evaluate> evaluate { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<staff> staff { get; set; }
    }
}
