//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string staffName { get; set; }
        public string staffLastname { get; set; }
        public string staffAddress { get; set; }
        public int staffTel { get; set; }
        public string staffUsername { get; set; }
        public string staffPassword { get; set; }
    }
}
